### ISSUE TITLE
"autonomousCommand" was removed as an error, but I have no idea what it was doing in the code.

### ISSUE THREAD

**Issue by UsaidPro** [UsaidPro/FRC-2015-Java-code#1]
There was an error where a variable called "autonomousCommand" was undefined. I declared it as a Command earlier in the code, which fixed the error. However, I don't know why it was there in the default robot code design when it was an error. If the reason for its existence is found, it would be nice, since right now it is a liability.

**Comment by smerkousdavid** [comment]
We can't do anything until we receive the robot back to test

**Comment by oliverwarne** [comment]
If we can't fix it yet, don't close it. 

Reopening

On-topic, maybe it's a variable that's supposed to be updated to whatever current autonomous command is currently running? I can't see the purpose for such a thing, but I have no clue. What java file is it under?

**Comment by UsaidPro** [comment]
It is a 'Command' object. If you go through the libaries that are imported, one of them has '.commands' at the end. That file is where the object is defined. The main issue I have with this is the fact that it was in the default code. Why put an error in a default template? I couldn't figure out why it existed at all, but someone can check it and post the reason if they figure it out. Perhaps we forgot to update wpilib or installation was incorrect . . . and that might explain why it is there.

**Comment by UsaidPro** [comment]
I found something out when I was looking at the 'Command' declaration. Apparently 'Command' is an abstract class that initializes (running a set of instructions once), then executes (commands in a loop), then exits. I think the reason 'autonomousCommand' existed is to provide a way for us to have more options in the initialization and execute parts without interfering with the  autonomous function that is called periodically. Also, it provides a way for us to check whether or not it is running because if 'autonomousCommand' is true, then autonomous has successfully run. 

So, what we are probably supposed to do is define a autonomousCommand.initialize() function which has the steps that we want to execute during autonomous. If we add anything which runs in a loop, we put define those actions in the autonomousCommand.execute() function.

Also, since we can check whether or not 'autonomousCommand' has successfully run, we can put a program to choose autonomous. We would have to add (after autonomousCommand.initialize() and .execute()):
if(autonomousCommand == false) // in other words, autonomousCommand failed to finish
{
     //run autonomous steps that we would do if we couldn't choose (default program)
}

Seems good?

EDIT: This won't work, see below

**Comment by UsaidPro** [comment]
Actually, I realized that won't work. 'Command' is an abstract class. Therefore, to use 'autonomousCommand' we have to create a class which inherits 'Command' and define all the functions there (Maybe call the class 'Autonomous'?). Then we instantiate a object called 'autonomousCommand', which would fix the error and give us the 'Command' class' functionality. Also, if we put the class as a branch in Github then we can use pull requests on the branch so that problems won't occur with multiple commits by different people at the same time. We might also add a 'Teleop' branch if we do an 'Autonomous' branch.

**Comment by smerkousdavid** [comment]
We should create another class to seperate Teleop and Autonomus and just call the classes within Robot.java
which would look like

autonomous.initialize().......

if autonomousCommand = false not runned

autonomous.stop() 

p.s. i dont know the command to stop a class from running but ill look it up

**Comment by UsaidPro** [comment]
I think we should also split up the Teleop and Autonomous classes into different branches which stem off the main branch. That way, we can work on Autonomous and Teleop at the same time without causing conflicts with commits.

**Comment by UsaidPro** [comment]
Btw, I feel like this discussion has deviated from the original problem. Maybe we should start using the wiki for ideas like making new classes, etc?

**Comment by smerkousdavid** [comment]
Wait can we do that, will the robot accept another class other than the 3 we have now?

**Comment by UsaidPro** [comment]
I think it can. Of course, we can't test it (need a simulator if we are to do it over the weekend), but FRC should allow us to create files which Robot.java includes and uses. Otherwise, what would be the point of having those extra "ExampleCommand.java" and "ExampleSubsystem.java" files which appear under the 'commands' and 'subsystems' folders? Putting an example indicates that they allow us to add files, because there won't be a need to have a example template for files that are not allowed to be created.
Should it be possible to use commands/subsystems, would we put the teleop/autonomous code as a command which is run or a subsystem which provides files for Robot.java (which is what I think they are used for, haven't looked them up yet).

**Comment by smerkousdavid** [comment]
I GOT IT! So what we do is create all our commands in the commands.java then call them out in Robot.java something like Teleop(command) then it would reference back to the commands then everything would look neater

**Comment by smerkousdavid** [comment]
Then we can run the same amount of code multiple times with a couple lines

**Comment by UsaidPro** [comment]
So "autonomousCommand" was just a placeholder for what command we would run to use autonomous . . .

**Comment by UsaidPro** [comment]
^Reason for this is since you thought of the 'command' autonomous/Teleop an hour ago, knowing how much you like to work on this stuff you are probably working on those files right now :stuck_out_tongue_closed_eyes:

**Comment by smerkousdavid** [comment]
Im actually going camping while coding, So ill get started in a little bit

**Comment by smerkousdavid** [comment]
I finished up the command system... So apparently this is how it works
There are 2 packages called subsystems and commands. 
commands you can call out in robot.java which would fix our problem like you said it is just a call from that package. so if i wanted to run a auton code i would change it in the auton command folder(which i just created) then in Robot.java i just put "Autonomous.start();" and it will run auton in auton... a little confusing...

The subsystems are things you would declare like Liftup or Liftdown you. So in subsystems you can declare what variables go where. like i wanted to say in a command Lift up for 2 seconds behind the lift up command is where you put how fast and what motor you want to send to
