### ISSUE TITLE
Notification - Addition of Meeting Date and Summaries

### ISSUE THREAD

**Issue by UsaidPro** [UsaidPro/FRC-2015-Java-code#10]
**I added Meeting Dates and Summaries to the Wiki in GitHub**. I did this since at the meeting (which I'm presently at) only I was there.
 To make sure that we all benefit from whatever information was put into the meeting, I put a new page into the wiki. Since I am not sure whether all of us look at it, I put it as a issue. 
**_Reply that you saw this_** and when everyone (in other words, David and Oliver) has replied, I will take this issue down.

**Comment by UsaidPro** [comment]
Also, maybe someone can improve the format of the Meeting page? Like splitting up the different bullets for Build, Coding, Marketing. I just got everything I possibly could get while starving, and it would be nice if someone could organize that list so we can find what we need to look at (I _tried_ to do this using italics to emphasize what us coders need to look at)

Also, note the list of ¨Leaders¨ to manage different projects to improve robot between now and Regionals

**Comment by oliverwarne** [comment]
Thank you for posting this. To clarify: The "leaders" are not permanent roles, and are simply the roles for us until we after competition?

**Comment by UsaidPro** [comment]
Yeah. These roles are only for planning/meetings until the competition in St. Louis.
