### ISSUE TITLE
Should we use pull requests?

### ISSUE THREAD

**Issue by UsaidPro** [UsaidPro/FRC-2015-Java-code#2]
I have noticed that no one is using them. It might be okay for now since we aren't on at the same time, but if we change a file and upload it after another has worked on it, then it would mean the other person's file is not up-to-date (and possibly invalid?). I feel like we need to start using pull requests if possible. However, if the file is pulled, only one person can work on it and others can not (which means if one of us forgets then the others can't work if that one person is unavailable).
Should we use them or not?

**Comment by smerkousdavid** [comment]
I had a problem with pull request because i kept getting a conflict error... don't know why?

**Comment by oliverwarne** [comment]
What we should be using is branches. For each change you make, you establish a new branch, and then merge it. That's when gits conflict checking works

**Comment by smerkousdavid** [comment]
Your the boss ;)

**Comment by UsaidPro** [comment]
I noticed David has not being using them after going through the branch -> pull request --> merge once, but other than remembering to do pull requests, there isn't much to add to this issue, so I'm closing it.
