### ISSUE TITLE
Has anyone found a simulator?

### ISSUE THREAD

**Issue by UsaidPro** [UsaidPro/FRC-2015-Java-code#3]
I found a simulator for FRC, however it is for Ubuntu Linux. The reason for a simulator is so that we can test our code without having to wait for build team to finish the robot, and we would be able to replicate our autonomous mode program. I noticed that in Eclipse there is a 'simulator' option but I 
haven't tried it yet.

**Comment by smerkousdavid** [comment]
We can use something like virtualbox and install ubuntu on there

**Comment by oliverwarne** [comment]
That'd be slow. We could go ahead and make a bootable usb. This is a non-permanent solution that would be just as fast as installing it as the operating system. If we wanted a permanent solution we could dual boot

http://www.pendrivelinux.com/yumi-multiboot-usb-creator/

**Comment by smerkousdavid** [comment]
Oliver I believe we should then just bring another computer because we would want to deploy at the same time. You know what we need to figure out if we can program all of this in linux?

**Comment by oliverwarne** [comment]
If you want to do this in linux, eclipse is already available. Don't see any reason why it wouldn't work. Just seems unnecessary

**Comment by smerkousdavid** [comment]
Ok we will figure it out once we get back

**Comment by UsaidPro** [comment]
Closing this for now due to postponement for when we meet

**Comment by smerkousdavid** [comment]
Why are you closing everything?
