### ISSUE TITLE
SmartDashboard in Java

### ISSUE THREAD

**Issue by UsaidPro** [UsaidPro/FRC-2015-Java-code#7]
I saw a comment that David did on another issue and decided to separate the ¨SmartDashboard¨ idea in another conversation. This is an enhancement to our Java program that we currently have no idea on whether or not it works. Should we attempt to make a 'SmartDashboard' in Java as well and test it with the robot code afterschool next week, or improve our robot code and leave SmartDashboard for after Spring Break?

**Comment by smerkousdavid** [comment]
I can't do anything right now because i was already assigned the commands. Do you think you or Oliver can do it

**Comment by UsaidPro** [comment]
I looked at SmartDashboard, and then found a bunch of random stuff. To put it simple, I found that SmartDashboard is already part of Eclipse (?) and how to edit it = no idea.

**Comment by smerkousdavid** [comment]
Its weird ik
