### ISSUE TITLE
We need to assign Roles

### ISSUE THREAD

**Issue by smerkousdavid** [UsaidPro/FRC-2015-Java-code#8]
I believe we are all working on the same thing I think we need something like one person take auton one teleop and the other like small management such as sensors and making it run faster.

**Comment by oliverwarne** [comment]
Sensors and other stuff seems easy. Do you know if there's any documentation regarding sensors? I couldn't find any in WPIlib

**Comment by smerkousdavid** [comment]
I just look at other teams code

**Comment by UsaidPro** [comment]
Sensors come with their own documentation which needs to be found online (like Talon had its own functions). We need to know what sensors we are attaching before we attempt to add any functions/find documentation.

**Comment by smerkousdavid** [comment]
I agree with Usaid we will program sensors later
