### ISSUE TITLE
Toggle on Auto

### ISSUE THREAD

**Issue by smerkousdavid** [UsaidPro/FRC-2015-Java-code#9]
I just made a toggle in Auto I don't know if it works but can some on look over it and check to see it it works

**Comment by UsaidPro** [comment]
I have checked it. Seems like it would work. We might want to add the DIO pins in SmartDashboard which edits RobotMap.java (if possible).

**Comment by smerkousdavid** [comment]
Ok sure

**Comment by smerkousdavid** [comment]
Usaid i was wondering could we create our own class in a separate folder for Smartdashboard or do we have to use the one that's built in
